### ISSUE TITLE
Unable to build firmware

### ISSUE THREAD

**Issue by caixiaohai0** [phobos-/PhobosLT#1]
Processing PhobosLT (framework: arduino; platform: espressif32@5.2.0; board: esp32dev)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (5.2.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20005.220925 (2.0.5)
 - tool-esptoolpy @ 1.40201.0 (4.2.1)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 44 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ESPAsyncWebServer-esphome @ 3.0.0
|-- ArduinoJson @ 6.19.4
|-- DEBUG
|-- LED
|-- WEBSERVER
Building in release mode
Compiling .pio\build\PhobosLT\liba74\AsyncTCP-esphome\AsyncTCP.cpp.o
.pio/libdeps/PhobosLT/AsyncTCP-esphome/src/AsyncTCP.cpp:753:2: error: #else without #if
 #else
  ^~~~
.pio/libdeps/PhobosLT/AsyncTCP-esphome/src/AsyncTCP.cpp:755:2: error: #endif without #if
 #endif
  ^~~~~
.pio/libdeps/PhobosLT/AsyncTCP-esphome/src/AsyncTCP.cpp:1020: error: unterminated #if
 #if LWIP_IPV4 && LWIP_IPV6

.pio/libdeps/PhobosLT/AsyncTCP-esphome/src/AsyncTCP.cpp: In member function 'bool AsyncClient::connect(const char*, uint16_t)':
.pio/libdeps/PhobosLT/AsyncTCP-esphome/src/AsyncTCP.cpp:754:39: error: 'ip_addr_t' {aka 'struct ip_addr'} has no member named 'addr'; did you mean 'u_addr'?
         return connect(IPAddress(addr.addr), port);
                                       ^~~~
                                       u_addr
Compiling .pio\build\PhobosLT\FrameworkArduino\libb64\cdecode.c.o
Compiling .pio\build\PhobosLT\FrameworkArduino\libb64\cencode.c.o
Compiling .pio\build\PhobosLT\FrameworkArduino\main.cpp.o
Compiling .pio\build\PhobosLT\FrameworkArduino\stdlib_noniso.c.o
Compiling .pio\build\PhobosLT\FrameworkArduino\wiring_pulse.c.o
Compiling .pio\build\PhobosLT\FrameworkArduino\wiring_shift.c.o
*** [.pio\build\PhobosLT\liba74\AsyncTCP-esphome\AsyncTCP.cpp.o] Error 1
============================================================================== [FAILED] Took 11.06 seconds ==============================================================================

**Comment by caixiaohai0** [comment]
When I try to build the firmware, it shows the error above, what step am I doing wrong?

**Comment by phobos-** [comment]
Hey, thank you for spotting this. The problem was with AsyncTCP version that recently has been bumped to 2.1.0. I added an explicit dependency on 2.0.1 to fix the problem. 

Here is the original issue:
https://github.com/esphome/issues/issues/5258

Here is my fix:
https://github.com/phobos-/PhobosLT/commit/ebac87fa705b17e784c25d2093556ea0d34bc4df

**Comment by caixiaohai0** [comment]
> Hey, thank you for spotting this. The problem was with AsyncTCP version that recently has been bumped to 2.1.0. I added an explicit dependency on 2.0.1 to fix the problem.
> 
> Here is the original issue: [esphome/issues#5258](https://github.com/esphome/issues/issues/5258)
> 
> Here is my fix: [ebac87f](https://github.com/phobos-/PhobosLT/commit/ebac87fa705b17e784c25d2093556ea0d34bc4df)
The Discord invitation has expired, can you update it again?

**Comment by phobos-** [comment]
> > Hey, thank you for spotting this. The problem was with AsyncTCP version that recently has been bumped to 2.1.0. I added an explicit dependency on 2.0.1 to fix the problem.
> > Here is the original issue: [esphome/issues#5258](https://github.com/esphome/issues/issues/5258)
> > Here is my fix: [ebac87f](https://github.com/phobos-/PhobosLT/commit/ebac87fa705b17e784c25d2093556ea0d34bc4df)
> > The Discord invitation has expired, can you update it again?

done
